/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema.estacionamento.pkg1;

import java.awt.BorderLayout;
import java.awt.Toolkit;
import static javax.swing.GroupLayout.Alignment.CENTER;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author rober
 */
public class TelaPagamento extends javax.swing.JFrame {
    
    private final double[][] precos = {
        {12.00, 9.00, 7.00, 15.00},   // Por Hora
        {75.00, 54.00, 35.00, 90.00},  // Por Dia
        {375.00, 270.00, 175.00, 450.00}, // Por Semana
        {1200.00, 900.00, 600.00, 1500.00} // Por Mês
    };
 
    /**
     * Creates new form TelaPagamento
     */
    public TelaPagamento() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btvisitante = new javax.swing.JButton();
        btfuncionario = new javax.swing.JButton();
        btpcd = new javax.swing.JButton();
        btppl = new javax.swing.JButton();
        txttempo = new javax.swing.JTextField();
        btformadepag = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pagamento");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tipo de Vaga");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tempo de estadia");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btvisitante.setForeground(new java.awt.Color(0, 0, 0));
        btvisitante.setText("Visitante");
        btvisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvisitanteActionPerformed(evt);
            }
        });

        btfuncionario.setForeground(new java.awt.Color(0, 0, 0));
        btfuncionario.setText("Funcionário");
        btfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfuncionarioActionPerformed(evt);
            }
        });

        btpcd.setForeground(new java.awt.Color(0, 0, 0));
        btpcd.setText("PCD");
        btpcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpcdActionPerformed(evt);
            }
        });

        btppl.setForeground(new java.awt.Color(0, 0, 0));
        btppl.setText("Pessoas de fora");
        btppl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpplActionPerformed(evt);
            }
        });

        txttempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttempoActionPerformed(evt);
            }
        });

        btformadepag.setForeground(new java.awt.Color(0, 0, 0));
        btformadepag.setText("Forma de Pagamento");
        btformadepag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btformadepagActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btvisitante)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btfuncionario)
                        .addGap(48, 48, 48)
                        .addComponent(btpcd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btppl)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btformadepag)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(txttempo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btfuncionario)
                        .addComponent(btvisitante)
                        .addComponent(btpcd)
                        .addComponent(btppl)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btformadepag)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(546, 321));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btvisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvisitanteActionPerformed
        // TODO add your handling code here:
       float taxa;
        float multiplicador = 0;
       float total = 0;
       float tempo = Float.parseFloat(txttempo.getText());
      if (tempo >= 1 && tempo <= 5) {
            total = tempo * 12;
            
      }else if ( tempo >= 6 && tempo<= 11) {
           total = tempo * 20;
                }
      else if ( tempo >=12 && tempo<=17){
          total =tempo * 30;
      }
      else if ( tempo >=18 && tempo<=23){
          total =tempo * 35;
      }
      else if(tempo >= 24) {
          JOptionPane.showMessageDialog(null,"Não é possivel passar mais de 24 horas neste estacionamento.", "Tempo Excedido",0);
                    
      }
      
       txtTotal.setText("R$ " + total);
        
    }//GEN-LAST:event_btvisitanteActionPerformed

    private void btfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfuncionarioActionPerformed
        // TODO add your handling code here:  float taxa;
       float taxa;
        float multiplicador = 0;
       float total = 0;
       float tempo = Float.parseFloat(txttempo.getText());
         if (tempo >= 1 && tempo <= 5) {
            total = tempo * 10;
            
      }else if ( tempo >= 6 && tempo<= 11) {
           total = tempo * 18;
      }
           else if  ( tempo >=12 && tempo<=17){
          total =tempo * 25;
      }
      else if ( tempo >=17 && tempo<=23){
          total =tempo * 30;
      }
      else if(tempo >= 24) {
          JOptionPane.showMessageDialog(null,"Não é possivel passar mais de 24 horas neste estacionamento.", "Tempo Excedido",0);
         } 
txtTotal.setText("R$ " + total);
    }//GEN-LAST:event_btfuncionarioActionPerformed

    private void btpcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpcdActionPerformed
        // TODO add your handling code here:
         float taxa;
        float multiplicador = 0;
       float total = 0;
       float tempo = Float.parseFloat(txttempo.getText());
         if (tempo >= 1 && tempo <= 5) {
            total = tempo * 5;
            
      }else if ( tempo >= 6 && tempo<= 11) {
           total = tempo * 10;
      }
           else if  ( tempo >=12 && tempo<=17){
          total =tempo * 15;
      }
      else if ( tempo >=17 && tempo<=23){
          total =tempo * 18;
      }
      else if(tempo >= 24) {
          JOptionPane.showMessageDialog(null,"Não é possivel passar mais de 24 horas neste estacionamento.", "Tempo Excedido",0);
         } 
txtTotal.setText("R$ " + total);
    }//GEN-LAST:event_btpcdActionPerformed

    private void btpplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpplActionPerformed
        // TODO add your handling code here:
         float taxa;
        float multiplicador = 0;
       float total = 0;
       float tempo = Float.parseFloat(txttempo.getText());
         if (tempo >= 1 && tempo <= 5) {
            total = tempo * 12;
            
      }else if ( tempo >= 6 && tempo<= 11) {
           total = tempo * 20;
      }
           else if  ( tempo >=12 && tempo<=17){
          total =tempo * 28;
      }
      else if ( tempo >=17 && tempo<=23){
          total =tempo * 36;
      }
      else if(tempo >= 24) {
          JOptionPane.showMessageDialog(null,"Não é possivel passar mais de 24 horas neste estacionamento.", "Tempo Excedido",0);
         } 
txtTotal.setText("R$ " + total);
    }//GEN-LAST:event_btpplActionPerformed

    private void txttempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttempoActionPerformed

    private void btformadepagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btformadepagActionPerformed
        // TODO add your handling code here:
               new FormaPagamento().setVisible(true);
                       dispose();


    }//GEN-LAST:event_btformadepagActionPerformed

    /**
     * @param args the command line arguments
     */
    
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamento().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btformadepag;
    private javax.swing.JButton btfuncionario;
    private javax.swing.JButton btpcd;
    private javax.swing.JButton btppl;
    private javax.swing.JButton btvisitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txttempo;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
               setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logoRM.png")));

    }
}
